contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: 1.0.2
    packID: RecordedFuture
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: Entity Reputation using sub-playbooks
id: Recorded Future IOC Reputation
inputs:
- description: The IP addresses to enrich
  key: IP
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Address
      root: IP
      transformers:
      - operator: uniq
- description: MD5 to enrich
  key: MD5
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
      transformers:
      - operator: uniq
- description: SHA256 to enrich
  key: SHA256
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
      transformers:
      - operator: uniq
- description: SHA1 to enrich
  key: SHA1
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA1
      root: File
      transformers:
      - operator: uniq
- description: URL to enrich
  key: URL
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Data
      root: URL
      transformers:
      - operator: uniq
- description: The domain name to enrich
  key: Domain
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Name
      root: Domain
      transformers:
      - operator: uniq
name: Recorded Future IOC Reputation
outputs:
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
  type: string
- contextPath: DBotScore.Type
  description: Indicator type
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: CVE.ID
  description: Vulnerability name
  type: string
- contextPath: Domain.Name
  description: Domain name
  type: string
- contextPath: Domain.Malicious.Vendor
  description: For malicious domains, the vendor that made the decision
  type: string
- contextPath: Domain.Malicious.Description
  description: For malicious domains, the reason that the vendor made the decision
  type: string
- contextPath: IP.Address
  description: IP address
  type: string
- contextPath: IP.Malicious.Vendor
  description: For malicious IP addresses, the vendor that made the decision
  type: string
- contextPath: IP.Malicious.Description
  description: For malicious IP addresses, the reason that the vendor made the decision
  type: string
- contextPath: URL.Data
  description: URL name
  type: string
- contextPath: URL.Malicious.Vendor
  description: For malicious URLs, the vendor that made the decision
  type: string
- contextPath: URL.Malicious.Description
  description: For malicious URLs, the reason that the vendor made the decision
  type: string
- contextPath: File.SHA256
  description: File SHA-256
  type: string
- contextPath: File.SHA512
  description: File SHA-512
  type: string
- contextPath: File.SHA1
  description: File SHA-1
  type: string
- contextPath: File.MD5
  description: File MD5
  type: string
- contextPath: File.CRC32
  description: File CRC32
  type: string
- contextPath: File.CTPH
  description: File CTPH
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: File.Malicious.Description
  description: For malicious files, the reason that the vendor made the decision
  type: string
- contextPath: RecordedFuture.File.riskScore
  description: Recorded Future Hash Risk Score
  type: number
- contextPath: RecordedFuture.File.riskLevel
  description: Recorded Future Hash Risk Level
  type: string
- contextPath: RecordedFuture.File.Evidence.rule
  description: Recorded Future Risk Rule Name
  type: string
- contextPath: RecordedFuture.File.Evidence.mitigation
  description: Recorded Future Risk Rule Mitigation
  type: string
- contextPath: RecordedFuture.File.Evidence.description
  description: Recorded Future Risk Rule description
  type: string
- contextPath: RecordedFuture.File.Evidence.timestamp
  description: Recorded Future Risk Rule timestamp
  type: date
- contextPath: RecordedFuture.File.Evidence.level
  description: Recorded Future Risk Rule Level
  type: number
- contextPath: RecordedFuture.File.Evidence.ruleid
  description: Recorded Future Risk Rule ID
  type: string
- contextPath: RecordedFuture.File.name
  description: Hash
  type: string
- contextPath: RecordedFuture.File.maxRules
  description: Maximum count of Recorded Future Hash Risk Rules
  type: number
- contextPath: RecordedFuture.File.ruleCount
  description: Number of triggered Recorded Future Hash Risk Rules
  type: number
- contextPath: RecordedFuture.IP.riskScore
  description: Recorded Future IP Risk Score
  type: number
- contextPath: RecordedFuture.IP.riskLevel
  description: Recorded Future IP Risk Level
  type: string
- contextPath: RecordedFuture.IP.Evidence.rule
  description: Recorded Future Risk Rule Name
  type: string
- contextPath: RecordedFuture.IP.Evidence.mitigation
  description: Recorded Future Risk Rule Mitigation
  type: string
- contextPath: RecordedFuture.IP.Evidence.description
  description: Recorded Future Risk Rule Description
  type: string
- contextPath: RecordedFuture.IP.Evidence.timestamp
  description: Recorded Future Risk Rule Timestamp
  type: date
- contextPath: RecordedFuture.IP.Evidence.level
  description: Recorded Future Risk Rule Level
  type: number
- contextPath: RecordedFuture.IP.Evidence.ruleid
  description: Recorded Future Risk Rule ID
  type: string
- contextPath: RecordedFuture.IP.name
  description: IP Address
  type: string
- contextPath: RecordedFuture.IP.maxRules
  description: Maximum count of Recorded Future IP Risk Rules
  type: number
- contextPath: RecordedFuture.IP.ruleCount
  description: Number of triggered Recorded Future IP Risk Rules
  type: number
- contextPath: RecordedFuture.CVE.riskLevel
  description: Recorded Future Vulnerability Risk Level
  type: string
- contextPath: RecordedFuture.CVE.riskScore
  description: Risk Score
  type: number
- contextPath: RecordedFuture.CVE.Evidence.rule
  description: Recorded Future Risk Rule Name
  type: string
- contextPath: RecordedFuture.CVE.Evidence.mitigation
  description: Recorded Future Risk Rule Mitigation
  type: string
- contextPath: RecordedFuture.CVE.Evidence.description
  description: Recorded Future Risk Rule description
  type: string
- contextPath: RecordedFuture.CVE.Evidence.timestamp
  description: Recorded Future Risk Rule timestamp
  type: date
- contextPath: RecordedFuture.CVE.Evidence.level
  description: Recorded Future Risk Rule Level
  type: number
- contextPath: RecordedFuture.CVE.Evidence.ruleid
  description: Recorded Future Risk Rule ID
  type: string
- contextPath: RecordedFuture.CVE.name
  description: Vulnerability name
  type: string
- contextPath: RecordedFuture.CVE.maxRules
  description: Maximum count of Recorded Future Vulnerability Risk Rules
  type: number
- contextPath: RecordedFuture.CVE.ruleCount
  description: Number of triggered Recorded Future Vulnerability Risk Rules
  type: number
- contextPath: RecordedFuture.Domain.riskScore
  description: Recorded Future Domain Risk Score
  type: number
- contextPath: RecordedFuture.Domain.riskLevel
  description: Recorded Future Domain Risk Level
  type: string
- contextPath: RecordedFuture.Domain.Evidence.rule
  description: Recorded Future Risk Rule Name
  type: string
- contextPath: RecordedFuture.Domain.Evidence.mitigation
  description: Recorded Future Risk Rule Mitigation
  type: string
- contextPath: RecordedFuture.Domain.Evidence.description
  description: Recorded Future Risk Rule description
  type: string
- contextPath: RecordedFuture.Domain.Evidence.timestamp
  description: Recorded Future Risk Rule timestamp
  type: date
- contextPath: RecordedFuture.Domain.Evidence.level
  description: Recorded Future Risk Rule Level
  type: number
- contextPath: RecordedFuture.Domain.Evidence.ruleid
  description: Recorded Future Risk Rule ID
  type: string
- contextPath: RecordedFuture.Domain.name
  description: Domain name
  type: string
- contextPath: RecordedFuture.Domain.maxRules
  description: Maximum count of Recorded Future Domain Risk Rules
  type: number
- contextPath: RecordedFuture.Domain.ruleCount
  description: Number of triggered Recorded Future Domain Risk Rules
  type: number
- contextPath: RecordedFuture.URL.riskScore
  description: Recorded Future URL Risk Score
  type: number
- contextPath: RecordedFuture.URL.riskLevel
  description: Recorded Future URL Risk Level
  type: string
- contextPath: RecordedFuture.URL.Evidence.rule
  description: Recorded Future Risk Rule Name
  type: string
- contextPath: RecordedFuture.URL.Evidence.mitigation
  description: Recorded Future Risk Rule Mitigation
  type: string
- contextPath: RecordedFuture.URL.Evidence.description
  description: Recorded Future Risk Rule description
  type: string
- contextPath: RecordedFuture.URL.Evidence.timestamp
  description: Recorded Future Risk Rule timestamp
  type: date
- contextPath: RecordedFuture.URL.Evidence.level
  description: Recorded Future Risk Rule Level
  type: number
- contextPath: RecordedFuture.URL.Evidence.ruleid
  description: Recorded Future Risk Rule ID
  type: string
- contextPath: RecordedFuture.URL.name
  description: URL
  type: string
- contextPath: RecordedFuture.URL.maxRules
  description: Maximum count of Recorded Future URL Risk Rules
  type: number
- contextPath: RecordedFuture.URL.ruleCount
  description: Number of triggered Recorded Future URL Risk Rules
  type: number
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "17"
      - "16"
      - "18"
      - "19"
      - "20"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 31873721-cbc2-4aff-89c6-8158aceb2f04
      iscommand: false
      name: ""
      version: -1
    taskid: 31873721-cbc2-4aff-89c6-8158aceb2f04
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 280,
          "y": 70
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a6d14c3d-59ff-4c4e-828b-a21492d4d1da
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: a6d14c3d-59ff-4c4e-828b-a21492d4d1da
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 280,
          "y": 520
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: c0323bab-06fc-49a3-8c75-c0a42de70554
      iscommand: false
      name: Recorded Future Domain Reputation
      playbookId: Recorded Future Domain Reputation
      type: playbook
      version: -1
    taskid: c0323bab-06fc-49a3-8c75-c0a42de70554
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -130,
          "y": 260
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 7fea0d9b-6f98-4ec4-81b0-cdadd6c749ad
      iscommand: false
      name: Recorded Future IP Reputation
      playbookId: Recorded Future IP Reputation
      type: playbook
      version: -1
    taskid: 7fea0d9b-6f98-4ec4-81b0-cdadd6c749ad
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -540,
          "y": 260
        }
      }
  "18":
    id: "18"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: ca55d1ff-d524-4456-8365-5b655de0b4a0
      iscommand: false
      name: Recorded Future URL Reputation
      playbookId: Recorded Future URL Reputation
      type: playbook
      version: -1
    taskid: ca55d1ff-d524-4456-8365-5b655de0b4a0
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 690,
          "y": 260
        }
      }
  "19":
    id: "19"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 8c9869fa-477d-4b6b-8e86-b37121adea91
      iscommand: false
      name: Recorded Future File Reputation
      playbookId: Recorded Future File Reputation
      type: playbook
      version: -1
    taskid: 8c9869fa-477d-4b6b-8e86-b37121adea91
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1100,
          "y": 260
        }
      }
  "20":
    id: "20"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      CVE:
        complex:
          accessor: ID
          root: CVE
          transformers:
          - operator: uniq
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: da774399-ce73-4369-89ae-1ad2be7c3130
      iscommand: false
      name: Recorded Future CVE Reputation
      playbookId: Recorded Future CVE Reputation
      type: playbook
      version: -1
    taskid: da774399-ce73-4369-89ae-1ad2be7c3130
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 280,
          "y": 260
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 515,
        "width": 2020,
        "x": -540,
        "y": 70
      }
    }
  }
