contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: 1.8.5
    packID: CommonPlaybooks
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: Detonate URL through active integrations that support URL detonation
id: detonate_url_-_generic
inputs:
- description: URL object of url to be detonated.
  key: URL
  playbookInputQuery: null
  required: false
  value:
    complex:
      root: URL
name: Detonate URL - Generic
outputs:
- contextPath: File
  description: The File's object
  type: unknown
- contextPath: File.Name
  description: Filename
  type: string
- contextPath: File.Size
  description: File size
  type: number
- contextPath: File.Type
  description: File type e.g. "PE" (only in case of report type=json)
  type: string
- contextPath: File.SHA256
  description: SHA256 of the file
  type: string
- contextPath: File.SHA1
  description: SHA1 of the file
  type: string
- contextPath: File.MD5
  description: MD5 of the file
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: File.Malicious.Description
  description: For malicious files, the reason for the vendor to make the decision
  type: string
- contextPath: DBotScore
  description: The Indicator's object
  type: unknown
- contextPath: DBotScore.Type
  description: The type of the indicator
  type: string
- contextPath: DBotScore.Indicator
  description: The indicator we tested
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: Joe.Analysis.WebID
  description: Web ID
  type: string
- contextPath: Joe.Analysis.Status
  description: Analysis Status
  type: string
- contextPath: Joe.Analysis.Comments
  description: Analysis Comments
  type: string
- contextPath: Joe.Analysis.Time
  description: Submitted Time
  type: date
- contextPath: Joe.Analysis.Runs
  description: Sub-Analysis Information
  type: unknown
- contextPath: Joe.Analysis.Result
  description: Analysis Results
  type: string
- contextPath: Joe.Analysis.Errors
  description: Raised errors during sampling
  type: unknown
- contextPath: Joe.Analysis.Systems
  description: Analysis OS
  type: unknown
- contextPath: Joe.Analysis.MD5
  description: MD5 of analysis sample
  type: string
- contextPath: Joe.Analysis.SHA1
  description: SHA1 of analysis sample
  type: string
- contextPath: Joe.Analysis.SHA256
  description: SHA256 of analysis sample
  type: string
- contextPath: Joe.Analysis.SampleName
  description: Sample Data, could be a file name or URL
  type: string
- contextPath: InfoFile.Name
  description: FileName
  type: string
- contextPath: InfoFile.EntryID
  description: The EntryID of the sample
  type: string
- contextPath: InfoFile.Size
  description: File Size
  type: number
- contextPath: InfoFile.Type
  description: File type e.g. "PE"
  type: string
- contextPath: InfoFile.Info
  description: Basic information of the file
  type: string
- contextPath: Sample.State
  description: The sample state
  type: string
- contextPath: Sample.ID
  description: The sample ID
  type: string
- contextPath: IP.Address
  description: IP's relevant to the sample
  type: string
- contextPath: InfoFile
  description: The report file's object
  type: unknown
- contextPath: Cuckoo.Task.Category
  description: Category of task
- contextPath: Cuckoo.Task.Machine
  description: Machine of task
- contextPath: Cuckoo.Task.Errors
  description: Errors of task
- contextPath: Cuckoo.Task.Target
  description: Target of task
- contextPath: Cuckoo.Task.Package
  description: Package of task
- contextPath: Cuckoo.Task.SampleID
  description: Sample ID of task
- contextPath: Cuckoo.Task.Guest
  description: Task guest
- contextPath: Cuckoo.Task.Custom
  description: Custom values of task
- contextPath: Cuckoo.Task.Owner
  description: Task owner
- contextPath: Cuckoo.Task.Priority
  description: Priority of task
- contextPath: Cuckoo.Task.Platform
  description: Platform of task
- contextPath: Cuckoo.Task.Options
  description: Task options
- contextPath: Cuckoo.Task.Status
  description: Task status
- contextPath: Cuckoo.Task.EnforceTimeout
  description: Is timeout of task enforced
- contextPath: Cuckoo.Task.Timeout
  description: Task timeout
- contextPath: Cuckoo.Task.Memory
  description: Task memory
- contextPath: Cuckoo.Task.Tags
  description: Task tags
- contextPath: Cuckoo.Task.ID
  description: ID of task
- contextPath: Cuckoo.Task.AddedOn
  description: Date on which the task was added
- contextPath: Cuckoo.Task.CompletedOn
  description: Date on which the task was completed
- contextPath: Cuckoo.Task.Score
  description: Reported score of the the task
- contextPath: Cuckoo.Task.Monitor
  description: Monitor of the reported task
- contextPath: ANYRUN.Task.AnalysisDate
  description: Date and time the analysis was executed.
  type: String
- contextPath: ANYRUN.Task.Behavior.Category
  description: Category of a process behavior.
  type: String
- contextPath: ANYRUN.Task.Behavior.Action
  description: Actions performed by a process.
  type: String
- contextPath: ANYRUN.Task.Behavior.ThreatLevel
  description: Threat score associated with a process behavior.
  type: Number
- contextPath: ANYRUN.Task.Behavior.ProcessUUID
  description: Unique ID of the process whose behaviors are being profiled.
  type: String
- contextPath: ANYRUN.Task.Connection.Reputation
  description: Connection reputation.
  type: String
- contextPath: ANYRUN.Task.Connection.ProcessUUID
  description: ID of the process that created the connection.
  type: String
- contextPath: ANYRUN.Task.Connection.ASN
  description: Connection autonomous system network.
  type: String
- contextPath: ANYRUN.Task.Connection.Country
  description: Connection country.
  type: String
- contextPath: ANYRUN.Task.Connection.Protocol
  description: Connection protocol.
  type: String
- contextPath: ANYRUN.Task.Connection.Port
  description: Connection port number.
  type: Number
- contextPath: ANYRUN.Task.Connection.IP
  description: Connection IP number.
  type: String
- contextPath: ANYRUN.Task.DnsRequest.Reputation
  description: Reputation of the DNS request.
  type: String
- contextPath: ANYRUN.Task.DnsRequest.IP
  description: IP addresses associated with a DNS request.
  type: Unknown
- contextPath: ANYRUN.Task.DnsRequest.Domain
  description: Domain resolution of a DNS request.
  type: String
- contextPath: ANYRUN.Task.Threat.ProcessUUID
  description: Unique process ID from where the threat originated.
  type: String
- contextPath: ANYRUN.Task.Threat.Msg
  description: Threat message.
  type: String
- contextPath: ANYRUN.Task.Threat.Class
  description: Class of the threat.
  type: String
- contextPath: ANYRUN.Task.Threat.SrcPort
  description: Port on which the threat originated.
  type: Number
- contextPath: ANYRUN.Task.Threat.DstPort
  description: Destination port of the threat.
  type: Number
- contextPath: ANYRUN.Task.Threat.SrcIP
  description: Source IP address where the threat originated.
  type: String
- contextPath: ANYRUN.Task.Threat.DstIP
  description: Destination IP address of the threat.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.Reputation
  description: Reputation of the HTTP request.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.Country
  description: HTTP request country.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.ProcessUUID
  description: ID of the process making the HTTP request.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.Body
  description: HTTP request body parameters and details.
  type: Unknown
- contextPath: ANYRUN.Task.HttpRequest.HttpCode
  description: HTTP request response code.
  type: Number
- contextPath: ANYRUN.Task.HttpRequest.Status
  description: Status of the HTTP request.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.ProxyDetected
  description: Whether the HTTP request was made through a proxy.
  type: Boolean
- contextPath: ANYRUN.Task.HttpRequest.Port
  description: HTTP request port.
  type: Number
- contextPath: ANYRUN.Task.HttpRequest.IP
  description: HTTP request IP address.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.URL
  description: HTTP request URL.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.Host
  description: HTTP request host.
  type: String
- contextPath: ANYRUN.Task.HttpRequest.Method
  description: HTTP request method type.
  type: String
- contextPath: ANYRUN.Task.FileInfo
  description: Details of the submitted file.
  type: String
- contextPath: ANYRUN.Task.OS
  description: OS of the sandbox in which the file was analyzed.
  type: String
- contextPath: ANYRUN.Task.ID
  description: The unique ID of the task.
  type: String
- contextPath: ANYRUN.Task.MIME
  description: The MIME of the file submitted for analysis.
  type: String
- contextPath: ANYRUN.Task.Verdict
  description: ANY.RUN verdict for the maliciousness of the submitted file or URL.
  type: String
- contextPath: ANYRUN.Task.Process.FileName
  description: File name of the process.
  type: String
- contextPath: ANYRUN.Task.Process.PID
  description: Process identification number.
  type: Number
- contextPath: ANYRUN.Task.Process.PPID
  description: Parent process identification number.
  type: Number
- contextPath: ANYRUN.Task.Process.ProcessUUID
  description: Unique process ID (used by ANY.RUN).
  type: String
- contextPath: ANYRUN.Task.Process.CMD
  description: Process command.
  type: String
- contextPath: ANYRUN.Task.Process.Path
  description: Path of the executed command.
  type: String
- contextPath: ANYRUN.Task.Process.User
  description: User who executed the command.
  type: String
- contextPath: ANYRUN.Task.Process.IntegrityLevel
  description: The process integrity level.
  type: String
- contextPath: ANYRUN.Task.Process.ExitCode
  description: Process exit code.
  type: Number
- contextPath: ANYRUN.Task.Process.MainProcess
  description: Whether the process is the main process.
  type: Boolean
- contextPath: ANYRUN.Task.Process.Version.Company
  description: Company responsible for the program executed.
  type: String
- contextPath: ANYRUN.Task.Process.Version.Description
  description: Description of the type of program.
  type: String
- contextPath: ANYRUN.Task.Process.Version.Version
  description: Version of the program executed.
  type: String
- contextPath: DBotScore.Indicator
  description: The indicator that was tested.
  type: String
- contextPath: DBotScore.Score
  description: The actual score.
  type: Number
- contextPath: DBotScore.Type
  description: Type of indicator.
  type: String
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score.
  type: String
- contextPath: URL.Data
  description: URL data.
  type: String
- contextPath: URL.Malicious.Vendor
  description: For malicious URLs, the vendor that made the decision.
  type: String
- contextPath: URL.Malicious.Description
  description: For malicious URLs, the reason for the vendor to make the decision.
  type: String
- contextPath: ANYRUN.Task.Status
  description: Task analysis status.
  type: String
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "11"
      - "13"
      - "12"
      - "14"
      - "15"
      - "16"
      - "17"
      - "18"
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Playbook start point
      id: ab416b1d-600a-47a5-89dc-64d0f0002db6
      iscommand: false
      name: ""
      version: -1
    taskid: ab416b1d-600a-47a5-89dc-64d0f0002db6
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 50
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Done
      id: 91ee56ee-91ac-4199-89fe-50ad796c6b02
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 91ee56ee-91ac-4199-89fe-50ad796c6b02
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Detonate one or more URLs using the Threat Grid integration. This
        playbook returns relevant reports to the War Room and URL reputations to the
        context data.
      id: 754e447b-20d7-4ab6-8713-97409910d090
      iscommand: false
      name: Detonate URL - ThreatGrid
      playbookName: Detonate URL - ThreatGrid
      type: playbook
      version: -1
    taskid: 754e447b-20d7-4ab6-8713-97409910d090
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Detonates a URL using the McAfee Advanced Threat Defense sandbox
        integration.
      id: 237ce1af-7984-4df7-8eea-e6577bf59c4a
      iscommand: false
      name: Detonate URL - McAfee ATD
      playbookName: Detonate URL - McAfee ATD
      type: playbook
      version: -1
    taskid: 237ce1af-7984-4df7-8eea-e6577bf59c4a
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: |-
        Detonates one or more URLs using the Joe Security sandbox integration.
        Returns relevant reports to the War Room and url reputations to the context data.
      id: 22124bae-451b-432b-88e6-1a9affb9ee16
      iscommand: false
      name: Detonate URL - JoeSecurity
      playbookName: Detonate URL - JoeSecurity
      type: playbook
      version: -1
    taskid: 22124bae-451b-432b-88e6-1a9affb9ee16
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Detonate one or more files using the Wildfire integration. This
        playbook returns relevant reports to the War Room and file reputations to
        the context data.
      id: a6e1e56f-f5da-4648-8b0c-a7e8d6122535
      iscommand: false
      name: Detonate URL - CrowdStrike
      playbookName: Detonate URL - CrowdStrike
      type: playbook
      version: -1
    taskid: a6e1e56f-f5da-4648-8b0c-a7e8d6122535
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 195
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Detonates a URL using the Lastline sandbox integration.
      id: 481f79ec-f360-4b69-8881-98b67f23eedb
      iscommand: false
      name: Detonate URL - Lastline v2
      playbookName: Detonate URL - Lastline v2
      type: playbook
      version: -1
    taskid: 481f79ec-f360-4b69-8881-98b67f23eedb
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 195
        }
      }
  "16":
    id: "16"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Detonates a file using Cuckoo sandbox
      id: 72dc0cac-36d3-49eb-8fb8-3e583202df61
      iscommand: false
      name: Detonate URL - Cuckoo
      playbookName: Detonate URL - Cuckoo
      type: playbook
      version: -1
    taskid: 72dc0cac-36d3-49eb-8fb8-3e583202df61
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 2200,
          "y": 195
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Detonates a URL using ANYRUN sandbox
      id: 527c7883-aab3-4641-87a1-296c5bc10806
      iscommand: false
      name: Detonate URL - ANYRUN
      playbookName: Detonate URL - ANYRUN
      type: playbook
      version: -1
    taskid: 527c7883-aab3-4641-87a1-296c5bc10806
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 2630,
          "y": 195
        }
      }
  "18":
    id: "18"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      Interval:
        simple: "1"
      Timeout:
        simple: "60"
      url:
        simple: ${URL.Data}
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: ae8130db-d640-476c-8509-caa0a3318d69
      iscommand: false
      name: Detonate URL - Group-IB TDS Polygon
      playbookName: Detonate URL - Group-IB TDS Polygon
      type: playbook
      version: -1
    taskid: ae8130db-d640-476c-8509-caa0a3318d69
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": -390,
          "y": 195
        }
      }
  "19":
    id: "19"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: '''Detonate one or more URLs using the CrowdStrike Falcon Sandbox
        integration.'''
      id: 07706e7e-800f-408e-8dfa-184841b701f4
      iscommand: false
      name: Detonate URL - CrowdStrike Falcon X
      playbookName: Detonate URL - CrowdStrike Falcon X
      type: playbook
      version: -1
    taskid: 07706e7e-800f-408e-8dfa-184841b701f4
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 3070,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 385,
        "width": 3840,
        "x": -390,
        "y": 50
      }
    }
  }
