contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: 1.0.2
    packID: RecordedFuture
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: Domain reputation using Recorded Future SOAR enrichment
id: Recorded Future Domain Reputation
inputs:
- description: The domain name to get reputation of.
  key: Domain
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Name
      root: Domain
name: Recorded Future Domain Reputation
outputs:
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
  type: string
- contextPath: DBotScore.Type
  description: Indicator type
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: Domain.Malicious.Vendor
  description: For malicious domains, the vendor that made the decision
  type: string
- contextPath: Domain.Malicious.Description
  description: For malicious domains, the reason that the vendor made the decision
  type: string
- contextPath: Domain.Name
  description: Domain name
  type: string
- contextPath: RecordedFuture.Domain.riskScore
  description: Recorded Future Domain Risk Score
  type: number
- contextPath: RecordedFuture.Domain.riskLevel
  description: Recorded Future Domain Risk Level
  type: string
- contextPath: RecordedFuture.Domain.Evidence.rule
  description: Recorded Future Risk Rule Name
  type: string
- contextPath: RecordedFuture.Domain.Evidence.mitigation
  description: Recorded Future Risk Rule Mitigation
  type: string
- contextPath: RecordedFuture.Domain.Evidence.description
  description: Recorded Future Risk Rule description
  type: string
- contextPath: RecordedFuture.Domain.Evidence.timestamp
  description: Recorded Future Risk Rule timestamp
  type: date
- contextPath: RecordedFuture.Domain.Evidence.level
  description: Recorded Future Risk Rule Level
  type: number
- contextPath: RecordedFuture.Domain.Evidence.ruleid
  description: Recorded Future Risk Rule ID
  type: string
- contextPath: RecordedFuture.Domain.name
  description: Domain name
  type: string
- contextPath: RecordedFuture.Domain.maxRules
  description: Maximum count of Recorded Future Domain Risk Rules
  type: number
- contextPath: RecordedFuture.Domain.ruleCount
  description: Number of triggered Recorded Future Domain Risk Rules
  type: number
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 89ea0694-d9c9-4ddf-8fd0-135f159afb57
      iscommand: false
      name: ""
      version: -1
    taskid: 89ea0694-d9c9-4ddf-8fd0-135f159afb57
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Domain
          operator: isExists
      label: "yes"
    id: "16"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "29"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether the playbook's input contains at least one domain
        name to enrich.
      id: 3c6fe423-8215-4bd0-8bf5-c57c35889637
      iscommand: false
      name: Is there a domain to enrich?
      type: condition
      version: -1
    taskid: 3c6fe423-8215-4bd0-8bf5-c57c35889637
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "24":
    id: "24"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9b1db93f-3933-43ee-89cd-df000c5047a2
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 9b1db93f-3933-43ee-89cd-df000c5047a2
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
  "26":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: containsString
                    right:
                      value:
                        simple: Recorded Future
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "26"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Recorded Future API
        integration enabled.
      id: 4729ec6c-7996-4e59-88c7-f9621b41d451
      iscommand: false
      name: Is Recorded Future API enabled?
      type: condition
      version: -1
    taskid: 4729ec6c-7996-4e59-88c7-f9621b41d451
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 410,
          "y": 505
        }
      }
  "28":
    id: "28"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      domain:
        complex:
          root: inputs.Domain
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Get a quick indication of the risk associated with a domain.
      id: 53bddf1a-a9f2-454c-8837-81e27976c8a7
      iscommand: true
      name: Get domain reputation from Recorded Future
      script: Recorded Future v2|||domain
      type: regular
      version: -1
    taskid: 53bddf1a-a9f2-454c-8837-81e27976c8a7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 410,
          "y": 730
        }
      }
  "29":
    id: "29"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8075d9ed-0723-4435-8018-09dc88e18081
      iscommand: false
      name: Get reputation using Recorded Future API
      type: title
      version: -1
    taskid: 8075d9ed-0723-4435-8018-09dc88e18081
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 410,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "16_24_#default#": 0.57,
      "26_24_#default#": 0.55,
      "26_28_yes": 0.61
    },
    "paper": {
      "dimensions": {
        "height": 880,
        "width": 740,
        "x": 50,
        "y": 50
      }
    }
  }
