contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: 1.8.5
    packID: CommonPlaybooks
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: "This playbook is used to block files from running on endpoints. \nThis
  playbook supports the following integrations:\n- Palo Alto Networks Traps\n- Cybereason\n-
  Carbon Black Enterprise Response\n- Cylance Protect v2\n"
id: Block File - Generic v2
inputs:
- description: The MD5 hash of the file you want to block.
  key: MD5
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
- description: ""
  key: SHA256
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
- description: Traps event ID that contains the malicious file to block.
  key: EventId
  playbookInputQuery: null
  required: false
  value: {}
name: Block File - Generic v2
outputs:
- contextPath: CbResponse.BlockedHashes.LastBlock.Time
  description: Last block time
- contextPath: CbResponse.BlockedHashes.LastBlock.Hostname
  description: Last block hostname
- contextPath: CbResponse.BlockedHashes.LastBlock.CbSensorID
  description: Last block sensor ID
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
      - "9"
      - "10"
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 420a534c-a6e6-4cf5-8b86-ac7dd1a91441
      iscommand: false
      name: ""
      version: -1
    taskid: 420a534c-a6e6-4cf5-8b86-ac7dd1a91441
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: 24babe11-954f-4415-8d3d-a1100cdbb3df
      iscommand: false
      name: Block File - Carbon Black Response
      playbookName: Block File - Carbon Black Response
      type: playbook
      version: -1
    taskid: 24babe11-954f-4415-8d3d-a1100cdbb3df
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c8476a84-8d87-4ff2-8d6c-1dd1cccc503a
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: c8476a84-8d87-4ff2-8d6c-1dd1cccc503a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 910,
          "y": 515
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook accepts an MD5 hash and blocks the file using the
        Cybereason integration.
      id: 2efe2a1a-1d31-438c-828f-b6ae50f3899d
      iscommand: false
      name: Block File - Cybereason
      playbookName: Block File - Cybereason
      type: playbook
      version: -1
    taskid: 2efe2a1a-1d31-438c-828f-b6ae50f3899d
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 480,
          "y": 340
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: This playbook accepts a SHA256 hash and adds the hash to the Global
        Quarantine list using the Cylance Protect v2 integration.
      id: a887370c-f94a-42f9-866f-2d80b7707f41
      iscommand: false
      name: Block File - Cylance Protect v2
      playbookName: Block File - Cylance Protect v2
      type: playbook
      version: -1
    taskid: a887370c-f94a-42f9-866f-2d80b7707f41
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 910,
          "y": 340
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: 4e936a4c-b781-40a1-831a-be0c62a727d6
      iscommand: false
      name: Traps Blacklist File
      playbookName: Traps Blacklist File
      type: playbook
      version: -1
    taskid: 4e936a4c-b781-40a1-831a-be0c62a727d6
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 340
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      id: ca09ee7f-ce03-43e9-8eed-0bfeef2b2ef3
      iscommand: false
      name: Traps Quarantine Event
      playbookName: Traps Quarantine Event
      type: playbook
      version: -1
    taskid: ca09ee7f-ce03-43e9-8eed-0bfeef2b2ef3
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 340
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "6"
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e46175f0-26fc-4f24-87f7-d531354ca0dd
      iscommand: false
      name: Palo Alto Networks - Traps
      type: title
      version: -1
    taskid: e46175f0-26fc-4f24-87f7-d531354ca0dd
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 195
        }
      }
  "9":
    id: "9"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 32d4b47a-e972-4e30-875b-b563130cc4ca
      iscommand: false
      name: Cybereason
      type: title
      version: -1
    taskid: 32d4b47a-e972-4e30-875b-b563130cc4ca
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0c07d0e1-59b1-436c-8e90-f2d0410df813
      iscommand: false
      name: Carbon Black Enterprise Response
      type: title
      version: -1
    taskid: 0c07d0e1-59b1-436c-8e90-f2d0410df813
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "11":
    id: "11"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: dcc8e191-213c-4ffd-8bc7-a8e1bc8894d7
      iscommand: false
      name: Cylance Protect v2
      type: title
      version: -1
    taskid: dcc8e191-213c-4ffd-8bc7-a8e1bc8894d7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 530,
        "width": 2100,
        "x": 50,
        "y": 50
      }
    }
  }
