contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: 1.0.3
    packID: Silverfort
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: This playbook gets an incident related to an account. If it is a domain
  admin, updates Silverfort risk.
id: Silverfort Update Risk for Domain Admins Incidents
inputs:
- description: Account Username
  key: Username
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Username
      root: Account
      transformers:
      - operator: uniq
name: Silverfort Update Risk for Domain Admins Incidents
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "18"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 193ff948-e457-4ab4-8183-9348c1c894c5
      iscommand: false
      name: ""
      version: -1
    taskid: 193ff948-e457-4ab4-8183-9348c1c894c5
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0d8c48d5-4deb-498e-859b-83da67f5621a
      iscommand: false
      name: Update User Risk in Silverfort
      type: title
      version: -1
    taskid: 0d8c48d5-4deb-498e-859b-83da67f5621a
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    scriptarguments:
      description:
        simple: Suspicious activity
      domain:
        complex:
          accessor: Users.dn}
          root: ${ActiveDirectory
          transformers:
          - args:
              error_if_no_match: {}
              ignore_case: {}
              multi_line: {}
              period_matches_newline: {}
              regex:
                value:
                  simple: DC=([^,]*)
            operator: RegexExtractAll
          - args:
              separator:
                value:
                  simple: .
            operator: join
      email: {}
      risk_name:
        simple: activity_risk
      sam_account:
        simple: ${ActiveDirectory.Users.sAMAccountName}
      severity:
        simple: medium
      upn: {}
      valid_for:
        simple: "1"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: User risk commands - update the user entity risk
      id: 6fc11e93-f83c-44e1-8fe6-e64fb2d27d58
      iscommand: true
      name: Update the user risk in Silverfort
      script: '|||silverfort-update-user-risk'
      type: regular
      version: -1
    taskid: 6fc11e93-f83c-44e1-8fe6-e64fb2d27d58
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "17"
    note: false
    quietmode: 0
    scriptarguments:
      Username:
        complex:
          root: inputs.Username
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Enrich accounts using one or more integrations.
        Supported integrations:
        - Active Directory
      id: 5c01d009-7c4b-4871-8a53-c9c6cf32cd7c
      iscommand: false
      name: Account Enrichment - Generic v2.1
      playbookId: Account Enrichment - Generic v2.1
      type: playbook
      version: -1
    taskid: 5c01d009-7c4b-4871-8a53-c9c6cf32cd7c
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 60,
          "y": 370
        }
      }
  "12":
    id: "12"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 18b08b98-887a-4f4c-8524-11a3938e0dd9
      iscommand: false
      name: Silverfort Risk Updated Successfully
      type: title
      version: -1
    taskid: 18b08b98-887a-4f4c-8524-11a3938e0dd9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1215
        }
      }
  "13":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: ADMembership
          operator: containsString
          right:
            value:
              simple: Domain Admins
      label: "yes"
    id: "13"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if the account is a domain admin
      id: 1839c91e-04a8-4f84-8103-6d5df7f3e190
      iscommand: false
      name: Is the Account a Domain Admin?
      type: condition
      version: -1
    taskid: 1839c91e-04a8-4f84-8103-6d5df7f3e190
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 60,
          "y": 720
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7459d73d-89fa-4483-804c-536b4964bb81
      iscommand: false
      name: Do Nothing
      type: title
      version: -1
    taskid: 7459d73d-89fa-4483-804c-536b4964bb81
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1c741b57-0f6f-41e8-8944-047c8df3c3e9
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: 1c741b57-0f6f-41e8-8944-047c8df3c3e9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1360
        }
      }
  "17":
    id: "17"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "13"
    note: false
    quietmode: 0
    scriptarguments:
      append: {}
      key:
        simple: ADMembership
      stringify: {}
      value:
        simple: ${ActiveDirectory.Users.memberOf}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Extract membership information from Active Directory
      id: ac1c41e2-21af-4ee1-882a-d779063f1373
      iscommand: false
      name: ExtractADMembership
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: ac1c41e2-21af-4ee1-882a-d779063f1373
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 60,
          "y": 545
        }
      }
  "18":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Silverfort
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "18"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if Silverfort is enabled
      id: 3e166dca-6dee-472e-8674-7a717b1b33d2
      iscommand: false
      name: Is Silverfort enabled ?
      type: condition
      version: -1
    taskid: 3e166dca-6dee-472e-8674-7a717b1b33d2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1375,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
