contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: 1.0.2
    packID: RecordedFuture
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: URL Enrichment using Recorded Future intelligence
id: Recorded Future URL Intelligence
inputs:
- description: The URL to enrich.
  key: URL
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Data
      root: URL
      transformers:
      - operator: uniq
name: Recorded Future URL Intelligence
outputs:
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
  type: string
- contextPath: DBotScore.Type
  description: Indicator type
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: IP.Address
  description: IP address
  type: string
- contextPath: IP.ASN
  description: ASN
  type: string
- contextPath: IP.Geo.Country
  description: IP Geolocation Country
  type: string
- contextPath: RecordedFuture.IP.criticality
  description: Risk Criticality
  type: number
- contextPath: RecordedFuture.IP.criticalityLabel
  description: Risk Criticality Label
  type: string
- contextPath: RecordedFuture.IP.riskString
  description: Risk String
  type: string
- contextPath: RecordedFuture.IP.riskSummary
  description: Risk Summary
  type: string
- contextPath: RecordedFuture.IP.rules
  description: Risk Rules
  type: string
- contextPath: RecordedFuture.IP.score
  description: Risk Score
  type: number
- contextPath: RecordedFuture.IP.firstSeen
  description: Evidence First Seen
  type: date
- contextPath: RecordedFuture.IP.lastSeen
  description: Evidence Last Seen
  type: date
- contextPath: RecordedFuture.IP.intelCard
  description: Recorded Future Intelligence Card URL
  type: string
- contextPath: RecordedFuture.IP.type
  description: Entity Type
  type: string
- contextPath: RecordedFuture.IP.name
  description: Entity
  type: string
- contextPath: RecordedFuture.IP.id
  description: Recorded Future Entity ID
  type: string
- contextPath: RecordedFuture.IP.location.asn
  description: ASN number
  type: string
- contextPath: RecordedFuture.IP.location.cidr.id
  description: Recorded Future CIDR ID
  type: string
- contextPath: RecordedFuture.IP.location.cidr.name
  description: CIDR
  type: string
- contextPath: RecordedFuture.IP.location.cidr.type
  description: CIDR Type
  type: string
- contextPath: RecordedFuture.IP.location.location.city
  description: IP Geolocation City
  type: string
- contextPath: RecordedFuture.IP.location.location.continent
  description: IP Geolocation Continent
  type: string
- contextPath: RecordedFuture.IP.location.location.country
  description: IP Geolocation Country
  type: string
- contextPath: RecordedFuture.IP.location.organization
  description: IP Geolocation Organization
  type: string
- contextPath: RecordedFuture.IP.metrics.type
  description: Recorded Future Metrics Type
  type: string
- contextPath: RecordedFuture.IP.metrics.value
  description: Recorded Future Metrics Value
  type: number
- contextPath: RecordedFuture.IP.threatLists.description
  description: Recorded Future Threat List Description
  type: string
- contextPath: RecordedFuture.IP.threatLists.id
  description: Recorded Future Threat List ID
  type: string
- contextPath: RecordedFuture.IP.threatLists.name
  description: Recorded Future Threat List Name
  type: string
- contextPath: RecordedFuture.IP.threatLists.type
  description: Recorded Future Threat List Type
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedAttacker.count
  description: Recorded Future Related Attacker Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedAttacker.id
  description: Recorded Future Related Attacker ID
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedAttacker.name
  description: Recorded Future Related Attacker Name
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedAttacker.type
  description: Recorded Future Related Attacker Type
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedTarget.count
  description: Recorded Future Related Target Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedTarget.id
  description: Recorded Future Related Target ID
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedTarget.name
  description: Recorded Future Related Target Name
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedTarget.type
  description: Recorded Future Related Target Type
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedThreatActor.count
  description: Recorded Future Related Threat Actor Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedThreatActor.id
  description: Recorded Future Related Threat Actor ID
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedThreatActor.name
  description: Recorded Future Related Threat Actor Name
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedThreatActor.type
  description: Recorded Future Related Threat Actor Type
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedMalware.count
  description: Recorded Future Related Malware Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedMalware.id
  description: Recorded Future Related Malware ID
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedMalware.name
  description: Recorded Future Related Malware Name
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedMalware.type
  description: Recorded Future Related Malware Type
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedCyberVulnerability.count
  description: Recorded Future Related Vulnerability Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedCyberVulnerability.id
  description: Recorded Future Related Vulnerability ID
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedCyberVulnerability.name
  description: Recorded Future Related Vulnerability Name
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedCyberVulnerability.type
  description: Recorded Future Related Vulnerability Type
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedIpAddress.count
  description: Recorded Future Related IP address Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedIpAddress.id
  description: Recorded Future Related IP address ID
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedIpAddress.name
  description: Recorded Future Related IP address Name
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedIpAddress.type
  description: Recorded Future Related IP address Type
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedInternetDomainName.count
  description: Recorded Future Related Domain Name Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedInternetDomainName.id
  description: Recorded Future Related Domain Name ID
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedInternetDomainName.name
  description: Recorded Future Related Domain Name Name
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedInternetDomainName.type
  description: Recorded Future Related Domain Name Type
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedProduct.count
  description: Recorded Future Related Product Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedProduct.id
  description: Recorded Future Related Product ID
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedProduct.name
  description: Recorded Future Related Product Name
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedProduct.type
  description: Recorded Future Related Product Type
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedCountries.count
  description: Recorded Future Related Countries Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedCountries.id
  description: Recorded Future Related Countries IDs
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedCountries.name
  description: Recorded Future Related Countries Names
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedCountries.type
  description: Recorded Future Related Countries Types
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedHash.count
  description: Recorded Future Related Hash Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedHash.id
  description: Recorded Future Related Hash ID
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedHash.name
  description: Recorded Future Related Hash Name
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedHash.type
  description: Recorded Future Related Hash Type
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedTechnology.count
  description: Recorded Future Related Technology Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedTechnology.id
  description: Recorded Future Related Technology ID
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedTechnology.name
  description: Recorded Future Related Technology Name
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedTechnology.type
  description: Recorded Future Related Technology Type
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedEmailAddress.count
  description: Recorded Future Related Email Address Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedEmailAddress.id
  description: Recorded Future Related Email Address ID
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedEmailAddress.name
  description: Recorded Future Related Email Address Name
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedEmailAddress.type
  description: Recorded Future Related Email Address Type
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedAttackVector.count
  description: Recorded Future Related Attack Vector Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedAttackVector.id
  description: Recorded Future Related Attack Vector ID
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedAttackVector.name
  description: Recorded Future Related Attack Vector Name
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedAttackVector.type
  description: Recorded Future Related Attack Vector Type
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedMalwareCategory.count
  description: Recorded Future Related Malware Category Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedMalwareCategory.id
  description: Recorded Future Related Malware Category ID
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedMalwareCategory.name
  description: Recorded Future Related Malware Category Name
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedMalwareCategory.type
  description: Recorded Future Related Malware Category Type
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedOperations.count
  description: Recorded Future Related Operations Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedOperations.id
  description: Recorded Future Related Operations ID
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedOperations.name
  description: Recorded Future Related Operations Name
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedOperations.type
  description: Recorded Future Related Operations Type
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedCompany.count
  description: Recorded Future Related Company Count
  type: number
- contextPath: RecordedFuture.IP.relatedEntities.RelatedCompany.id
  description: Recorded Future Related Operations ID
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedCompany.name
  description: Recorded Future Related Operations Name
  type: string
- contextPath: RecordedFuture.IP.relatedEntities.RelatedCompany.type
  description: Recorded Future Related Operations Type
  type: string
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b50e0577-4b53-4047-81cd-98a1f39b4e45
      iscommand: false
      name: ""
      version: -1
    taskid: b50e0577-4b53-4047-81cd-98a1f39b4e45
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.URL
          operator: isExists
      label: "yes"
    id: "16"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "35"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: inputs.url
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Do we have a url to check
      id: 6e674458-38fe-4444-8f45-9d7a3722e1c7
      iscommand: false
      name: Is there a URL to get reputation of?
      type: condition
      version: -1
    taskid: 6e674458-38fe-4444-8f45-9d7a3722e1c7
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 200
        }
      }
  "24":
    id: "24"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 30f3ff5b-5922-4260-821d-0faccc04cc9f
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 30f3ff5b-5922-4260-821d-0faccc04cc9f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
  "35":
    id: "35"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "36"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 739989e4-4116-4083-80d1-7797ec9e9e15
      iscommand: false
      name: Get reputation using Recorded Future API
      type: title
      version: -1
    taskid: 739989e4-4116-4083-80d1-7797ec9e9e15
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 360,
          "y": 370
        }
      }
  "36":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: containsString
                    right:
                      value:
                        simple: Recorded Future
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "36"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "37"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Recorded Future API
        enabled.
      id: 389dc4be-95dc-4f92-862b-221d91282c4c
      iscommand: false
      name: Is Recorded Future API enabled?
      type: condition
      version: -1
    taskid: 389dc4be-95dc-4f92-862b-221d91282c4c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 360,
          "y": 505
        }
      }
  "37":
    id: "37"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    scriptarguments:
      entity:
        simple: ${inputs.URL}
      entity_type:
        simple: url
      fetch_related_entities:
        simple: "yes"
      fetch_riskyCIDRips:
        simple: "no"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Get threat intelligence for an IP, domain, CVE, URL, or file.
      id: 5dbf3e09-a766-417b-8327-4f5ce4df0fc3
      iscommand: true
      name: Get URL intelligence from Recorded Future
      script: Recorded Future v2|||recordedfuture-intelligence
      type: regular
      version: -1
    taskid: 5dbf3e09-a766-417b-8327-4f5ce4df0fc3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 360,
          "y": 690
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 880,
        "width": 690,
        "x": 50,
        "y": 50
      }
    }
  }
