contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: 1.1.6
    packID: TIM_Processing
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: |-
  This playbook tags indicators ingested by feeds that require manual approval. The playbook is triggered due to a job. The indicators are tagged as requiring a manual review. The playbook optionally concludes with creating a new incident that includes all of the indicators that the analyst must review.
  To enable the playbook, the indicator query needs to be configured. An example query is a list of the feeds whose ingested indicators should be manually reviewed. For example, sourceBrands:"Feed A" or sourceBrands:"Feed B".
id: TIM - Process Indicators - Manual Review
inputs:
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: ""
    queryEntity: indicators
    results: null
    runFromLastJobTime: false
  required: false
  value: {}
- description: This input determines if processed indicators that have the manual
    review tag are reviewed in a new incident. To create an incident, enter any value
    other than 'No'.
  key: OpenIncidentToReviewIndicatorsManually
  playbookInputQuery: null
  required: true
  value:
    simple: "No"
name: TIM - Process Indicators - Manual Review
outputs: []
quiet: true
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: b59eeea0-db49-4725-8dac-8a7d383cef75
      iscommand: false
      name: ""
      version: -1
    taskid: b59eeea0-db49-4725-8dac-8a7d383cef75
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -290
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: playbookQuery.value
          operator: isNotEmpty
      label: "yes"
    id: "2"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a6ccee14-545f-4e11-8230-4b13f2ced84c
      iscommand: false
      name: Are there query results?
      type: condition
      version: -1
    taskid: a6ccee14-545f-4e11-8230-4b13f2ced84c
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": -140
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 248ee366-c269-479e-8679-5fc5131fce23
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 248ee366-c269-479e-8679-5fc5131fce23
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1030
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 2
    scriptarguments:
      accountid: {}
      accountname: {}
      activedirectoryaccountstatus: {}
      activedirectorydisplayname: {}
      activedirectorypasswordstatus: {}
      affecteddata: {}
      affecteddatatype: {}
      affectedindividualscontactinformation: {}
      agentid: {}
      app: {}
      approximatenumberofaffecteddatasubjects: {}
      assetid: {}
      assets: {}
      attachmentcount: {}
      attachmentextension: {}
      attachmenthash: {}
      attachmentid: {}
      attachmentname: {}
      attachmentsize: {}
      attachmenttype: {}
      blockedaction: {}
      bugtraq: {}
      city: {}
      clarotyalertresolved: {}
      clarotyalerttype: {}
      clarotycategory: {}
      clarotynetworkid: {}
      clarotyrelatedassets: {}
      clarotyresourceid: {}
      clarotysiteid: {}
      code42alerttype: {}
      code42fileevents: {}
      commandline: {}
      companyaddress: {}
      companycity: {}
      companycountry: {}
      companyhasinsuranceforthebreach: {}
      companyname: {}
      companypostalcode: {}
      companypropertystatus: {}
      contactaddress: {}
      contactname: {}
      coordinates: {}
      country: {}
      countrywherebusinesshasitsmainestablishment: {}
      countrywherethebreachtookplace: {}
      criticalassets: {}
      customFields: {}
      cve: {}
      cvss: {}
      dataencryptionstatus: {}
      datetimeofthebreach: {}
      dbotprediction: {}
      dbotpredictionprobability: {}
      dbottextsuggestionhighlighted: {}
      designmultiselect: {}
      designtags: {}
      dest: {}
      destinationip: {}
      destntdomain: {}
      details: {}
      detectionendtime: {}
      detectionid: {}
      detectionticketed: {}
      detectionupdatetime: {}
      detectionurl: {}
      devicegsuiteaccountstatus: {}
      devicename: {}
      dmcaasset: {}
      dmcadns: {}
      dmcafilename: {}
      dmcafilesize: {}
      dmcaipaddress: {}
      dmcalastseedate: {}
      dmcanoticeid: {}
      dmcaportid: {}
      dmcaprotocol: {}
      dmcatimestamp: {}
      dpoemailaddress: {}
      duoaccountstatus: {}
      duration: {}
      elasticdisc: {}
      emailaddress: {}
      emailauthenticitycheck: {}
      emailautoreply: {}
      emailbcc: {}
      emailbody: {}
      emailbody2: {}
      emailbodyformat: {}
      emailbodyhtml: {}
      emailcc: {}
      emailclassification: {}
      emailclientname: {}
      emailfrom: {}
      emailfrom2: {}
      emailheaders: {}
      emailhtml: {}
      emailinreplyto: {}
      emailkeywords: {}
      emailmessageid: {}
      emailreceived: {}
      emailreplyto: {}
      emailreturnpath: {}
      emailsenderip: {}
      emailsize: {}
      emailsource: {}
      emailsubject: {}
      emailsubject2: {}
      emailto: {}
      emailto2: {}
      emailtocount: {}
      emailurlclicked: {}
      employeedisplayname: {}
      employeeemail: {}
      employeemanageremail: {}
      entryIDs: {}
      exfiltratedfiles: {}
      expanseexposuretype: {}
      expanserawjsonevent: {}
      expanseseverity: {}
      extrahopapplianceid: {}
      extrahophostname: {}
      filehash: {}
      filename: {}
      filepath: {}
      filesize: {}
      firstseen: {}
      globaldirectoryvisibility: {}
      googleaccountstatus: {}
      googleadminrolesstatus: {}
      googledisplayname: {}
      googledrivestatus: {}
      googlemailstatus: {}
      googlepasswordstatus: {}
      hostname: {}
      indenideviceid: {}
      indeniissueid: {}
      infectedhosts: {}
      investigationstage: {}
      isolated: {}
      isthedatasubjecttodpia: {}
      justification: {}
      labels: {}
      lastmodifiedby: {}
      lastmodifiedon: {}
      lastseen: {}
      likelyimpact: {}
      mailboxdelegation: {}
      maliciousbehavior: {}
      maliciouscauseifthecauseisamaliciousattack: {}
      malwarefamily: {}
      measurestomitigate: {}
      name:
        simple: Review Indicators Manually
      newcompanysize: {}
      niststage: {}
      occurred: {}
      offboardingdate: {}
      offboardingstage: {}
      oktaaccountstatus: {}
      owner: {}
      parentprocessid: {}
      participants: {}
      phase: {}
      phishingsubtype: {}
      pid: {}
      policydeleted: {}
      policydescription: {}
      policydetails: {}
      policyid: {}
      policyrecommendation: {}
      policyremediable: {}
      policyseverity: {}
      policytype: {}
      possiblecauseofthebreach: {}
      postalcode: {}
      previouscoordinates: {}
      previouscountry: {}
      previoussignindatetime: {}
      previoussourceip: {}
      prismacloudcomputeactivitytype: {}
      prismacloudcomputeappid: {}
      prismacloudcomputecategory: {}
      prismacloudcomputecollections: {}
      prismacloudcomputecommand: {}
      prismacloudcomputecontainer: {}
      prismacloudcomputecredentialid: {}
      prismacloudcomputedistribution: {}
      prismacloudcomputeerror: {}
      prismacloudcomputeforensic: {}
      prismacloudcomputefqdn: {}
      prismacloudcomputefunction: {}
      prismacloudcomputehost: {}
      prismacloudcomputeimage: {}
      prismacloudcomputeinteractive: {}
      prismacloudcomputekubernetesresource: {}
      prismacloudcomputelabels: {}
      prismacloudcomputeline: {}
      prismacloudcomputelogfile: {}
      prismacloudcomputemarkdown: {}
      prismacloudcomputemessage: {}
      prismacloudcomputeproject: {}
      prismacloudcomputeprotected: {}
      prismacloudcomputeprovider: {}
      prismacloudcomputerawalertjson: {}
      prismacloudcomputeregion: {}
      prismacloudcomputeregistry: {}
      prismacloudcomputerule: {}
      prismacloudcomputeruntime: {}
      prismacloudcomputeservice: {}
      prismacloudcomputeservicetype: {}
      prismacloudcomputetotal: {}
      prismacloudcomputetype: {}
      prismacloudcomputeuser: {}
      prismacloudid: {}
      prismacloudreason: {}
      prismacloudrules: {}
      prismacloudstatus: {}
      prismacloudtime: {}
      rating: {}
      rawparticipants: {}
      region: {}
      regionid: {}
      reporteremailaddress: {}
      reputation: {}
      resourceapiname: {}
      resourcecloudtype: {}
      resourceid: {}
      resourcename: {}
      resourcetype: {}
      riskrating: {}
      riskscore: {}
      roles: {}
      rrn: {}
      searchresult: {}
      sectorofaffectedparty: {}
      severity: {}
      signature: {}
      signindatetime: {}
      sixgillalertid: {}
      sixgillcontent: {}
      sixgillthreatlevel: {}
      sixgillthreattype: {}
      sizenumberofemployees: {}
      sizeturnover: {}
      skuname: {}
      skutier: {}
      sla: {}
      slaField: {}
      source: {}
      sourcehostname: {}
      sourceip: {}
      src: {}
      srcntdomain: {}
      srcos: {}
      srcuser: {}
      subscriptionassignedby: {}
      subscriptioncreatedby: {}
      subscriptioncreatedon: {}
      subscriptiondescription: {}
      subscriptionid: {}
      subscriptionname: {}
      subscriptiontype: {}
      subscriptionupdatedby: {}
      subscriptionupdatedon: {}
      subtype: {}
      systemdefault: {}
      systems: {}
      tags: {}
      targetfirewallversion: {}
      telephoneno: {}
      terminatedaction: {}
      threatactor: {}
      threatintelsource: {}
      trapsid: {}
      travelmaplink: {}
      triggeredsecurityprofile: {}
      ttl: {}
      type:
        simple: Review Indicators Manually
      urlsslverification: {}
      user: {}
      usermine: {}
      username: {}
      vendorid: {}
      vendorproduct: {}
      vpcid: {}
      vulnerabilitycategory: {}
      whereisdatahosted: {}
      xdralertcount: {}
      xdralerts: {}
      xdrassigneduseremail: {}
      xdrassigneduserprettyname: {}
      xdrdescription: {}
      xdrdetectiontime: {}
      xdrfileartifacts: {}
      xdrhighseverityalertcount: {}
      xdrhostcount: {}
      xdrincidentid: {}
      xdrlowseverityalertcount: {}
      xdrmediumseverityalertcount: {}
      xdrnetworkartifacts: {}
      xdrnotes: {}
      xdrresolvecomment: {}
      xdrstatus: {}
      xdrurl: {}
      xdrusercount: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Creates an incident that includes all of the indicators that must
        be manually reviewed.
      id: 2dcdf680-2e84-4095-878b-35f80edb2a42
      iscommand: true
      name: Create Process Indicators Manually incident
      script: Builtin|||createNewIncident
      type: regular
      version: -1
    taskid: 2dcdf680-2e84-4095-878b-35f80edb2a42
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -30,
          "y": 860
        }
      }
  "5":
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: This playbook uses several sub playbooks to process and tag indicators,
        which is used to identify indicators that shouldn't be blacklisted. For example
        IP indicators that belong to business partners or important hashes we wish
        to not process. Additional sub playbooks can be added for improving the business
        logic and tagging according to the user's needs.
      id: 39a942f7-9326-4700-8900-e0bf16492f88
      iscommand: false
      name: TIM - Indicator Auto Processing
      playbookId: TIM - Indicator Auto Processing
      type: playbook
      version: -1
    taskid: 39a942f7-9326-4700-8900-e0bf16492f88
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 170,
          "y": 30
        }
      }
  "6":
    id: "6"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 2
    scriptarguments:
      field:
        simple: tags
      fieldValue:
        simple: pending_review
      indicatorsValues:
        simple: ${ProcessedIndicators}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Adds the 'pending_review' tag to the indicators.
      id: 84328535-4d96-4b52-8fe6-203310a485f4
      iscommand: true
      name: Tag indicators as pending review
      script: Builtin|||appendIndicatorField
      type: regular
      version: -1
    taskid: 84328535-4d96-4b52-8fe6-203310a485f4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 170,
          "y": 520
        }
      }
  "7":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: ProcessedIndicators
          operator: isNotEmpty
      label: "yes"
    id: "7"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 454fb12b-7e06-4720-8b62-24db965eae8e
      iscommand: false
      name: Are there processed indicators to tag for manual review?
      type: condition
      version: -1
    taskid: 454fb12b-7e06-4720-8b62-24db965eae8e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 170,
          "y": 170
        }
      }
  "8":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.OpenIncidentToReviewIndicatorsManually
          operator: isEqualString
          right:
            value:
              simple: "No"
      label: "no"
    id: "8"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "4"
      "no":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 524b8391-97d9-49c2-859a-dfc5909620f2
      iscommand: false
      name: Open manual review incident?
      type: condition
      version: -1
    taskid: 524b8391-97d9-49c2-859a-dfc5909620f2
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 170,
          "y": 690
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1385,
        "width": 860,
        "x": -30,
        "y": -290
      }
    }
  }
