contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: 1.1.12
    packID: HelloWorld
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: This is a playbook which will handle the alerts coming from the Hello
  World service
id: Handle Hello World Alert
inputs:
- description: Alert ID to retrieve details for. By default retrieves from the HelloWorld
    ID custom field in the HelloWorld incident type
  key: AlertID
  playbookInputQuery: null
  required: false
  value:
    simple: ${incident.helloworldid}
name: Handle Hello World Alert
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: "1"
      iscommand: false
      name: ""
      version: -1
    taskid: "1"
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    note: false
    quietmode: 0
    scriptarguments:
      alert_id:
        simple: ${inputs.AlertID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieve alert details for a HelloWorld alert by alert ID
      id: 7a16e30b-cd8b-45ce-81cd-b19f9c603dc0
      iscommand: true
      name: Get alert details
      script: '|||helloworld-get-alert'
      type: regular
      version: -1
    taskid: 7a16e30b-cd8b-45ce-81cd-b19f9c603dc0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 240,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
