contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: 1.0.2
    packID: RecordedFuture
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: File reputation using Recorded Future SOAR enrichment
id: Recorded Future File Reputation
inputs:
- description: MD5 hash for which to get the reputation.
  key: MD5
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
- description: SHA-256 hash for which to get the reputation.
  key: SHA256
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
- description: SHA-1 hash for which to get the reputation.
  key: SHA1
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA1
      root: File
name: Recorded Future File Reputation
outputs:
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
  type: string
- contextPath: DBotScore.Type
  description: Indicator type
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: File.SHA256
  description: File SHA-256
  type: string
- contextPath: File.SHA512
  description: File SHA-512
  type: string
- contextPath: File.SHA1
  description: File SHA-1
  type: string
- contextPath: File.MD5
  description: File MD5
  type: string
- contextPath: File.CRC32
  description: File CRC32
  type: string
- contextPath: File.CTPH
  description: File CTPH
  type: string
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: File.Malicious.Description
  description: For malicious files, the reason that the vendor made the decision
  type: string
- contextPath: RecordedFuture.File.riskScore
  description: Recorded Future Hash Risk Score
  type: number
- contextPath: RecordedFuture.File.riskLevel
  description: Recorded Future Hash Risk Level
  type: string
- contextPath: RecordedFuture.File.Evidence.rule
  description: Recorded Future Risk Rule Name
  type: string
- contextPath: RecordedFuture.File.Evidence.mitigation
  description: Recorded Future Risk Rule Mitigation
  type: string
- contextPath: RecordedFuture.File.Evidence.description
  description: Recorded Future Risk Rule description
  type: string
- contextPath: RecordedFuture.File.Evidence.timestamp
  description: Recorded Future Risk Rule timestamp
  type: date
- contextPath: RecordedFuture.File.Evidence.level
  description: Recorded Future Risk Rule Level
  type: number
- contextPath: RecordedFuture.File.Evidence.ruleid
  description: Recorded Future Risk Rule ID
  type: string
- contextPath: RecordedFuture.File.name
  description: Hash
  type: string
- contextPath: RecordedFuture.File.maxRules
  description: Maximum count of Recorded Future Hash Risk Rules
  type: number
- contextPath: RecordedFuture.File.ruleCount
  description: Number of triggered Recorded Future Hash Risk Rules
  type: number
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 23a78b35-39ae-4280-80fd-4692966313d3
      iscommand: false
      name: ""
      version: -1
    taskid: 23a78b35-39ae-4280-80fd-4692966313d3
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 500,
          "y": -200
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "14"
      - "15"
      - "17"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d3c732b7-1ebb-464c-813d-4ba3d092db01
      iscommand: false
      name: Get reputation using Recorded Future API
      type: title
      version: -1
    taskid: d3c732b7-1ebb-464c-813d-4ba3d092db01
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 500,
          "y": 195
        }
      }
  "5":
    continueonerror: true
    id: "5"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      file:
        complex:
          root: inputs.MD5
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Get a quick indication of the risk associated with a file.
      id: 4914716e-d3cc-4d8a-8bed-c8c3f66a3b8c
      iscommand: true
      name: Get MD5 reputation
      script: Recorded Future v2|||file
      type: regular
      version: -1
    taskid: 4914716e-d3cc-4d8a-8bed-c8c3f66a3b8c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 655
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7bb25a37-781b-437b-8286-7bb3162be1fa
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 7bb25a37-781b-437b-8286-7bb3162be1fa
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1920,
          "y": 950
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.MD5
          operator: isExists
      label: "yes"
    id: "14"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.MD5}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if there is an MD5 hash in context.
      id: 40e9afcb-fd99-47fc-85cd-b7494a8497b0
      iscommand: false
      name: Is there an MD5 hash?
      type: condition
      version: -1
    taskid: 40e9afcb-fd99-47fc-85cd-b7494a8497b0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
  "15":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.SHA256
          operator: isExists
      label: "yes"
    id: "15"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "16"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.SHA256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if there is a SHA-256 hash in context.
      id: 4caf0a1b-7bbe-4162-8918-a1390918de5a
      iscommand: false
      name: Is there a SHA-256 hash?
      type: condition
      version: -1
    taskid: 4caf0a1b-7bbe-4162-8918-a1390918de5a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 500,
          "y": 340
        }
      }
  "16":
    continueonerror: true
    id: "16"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      file:
        complex:
          root: inputs.SHA256
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Get a quick indication of the risk associated with a file.
      id: 667df526-d5c0-4ba7-8c04-91ec2bd925c5
      iscommand: true
      name: Get SHA-256 reputation
      script: Recorded Future v2|||file
      type: regular
      version: -1
    taskid: 667df526-d5c0-4ba7-8c04-91ec2bd925c5
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 500,
          "y": 665
        }
      }
  "17":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.SHA1
          operator: isExists
      label: "yes"
    id: "17"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "18"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: ${File.SHA256}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if there is a SHA-1 hash in context.
      id: fbf610f2-782a-48ec-8d05-8976f347dc7a
      iscommand: false
      name: Is there a SHA-1 hash?
      type: condition
      version: -1
    taskid: fbf610f2-782a-48ec-8d05-8976f347dc7a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 950,
          "y": 340
        }
      }
  "18":
    continueonerror: true
    id: "18"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    scriptarguments:
      file:
        complex:
          root: inputs.SHA1
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Get a quick indication of the risk associated with a file.
      id: 3831a085-c16b-4eec-8499-4852a0fd1f43
      iscommand: true
      name: Get SHA-1 reputation
      script: Recorded Future v2|||file
      type: regular
      version: -1
    taskid: 3831a085-c16b-4eec-8499-4852a0fd1f43
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 962.5,
          "y": 665
        }
      }
  "19":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: containsString
                    right:
                      value:
                        simple: Recorded Future
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "19"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Recorded Future API
        integration enabled.
      id: eb6380e9-cb99-4450-8190-c3be63dd1c1b
      iscommand: false
      name: Is Recorded Future API enabled?
      type: condition
      version: -1
    taskid: eb6380e9-cb99-4450-8190-c3be63dd1c1b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 500,
          "y": -70
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "14_7_#default#": 0.52,
      "15_7_#default#": 0.61
    },
    "paper": {
      "dimensions": {
        "height": 1215,
        "width": 2250,
        "x": 50,
        "y": -200
      }
    }
  }
