contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: 1.0.2
    packID: RecordedFuture
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: CVE reputation with Recorded Future SOAR enrichment.
id: Recorded Future CVE Reputation
inputs:
- description: The CVE ID for which to get the reputation.
  key: CVE
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: ID
      root: CVE
name: Recorded Future CVE Reputation
outputs:
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
  type: string
- contextPath: DBotScore.Type
  description: Indicator type
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: CVE.ID
  description: Vulnerability name
  type: string
- contextPath: RecordedFuture.CVE.riskLevel
  description: Recorded Future vulnerability risk level
  type: string
- contextPath: RecordedFuture.CVE.riskScore
  description: Risk score
  type: number
- contextPath: RecordedFuture.CVE.Evidence.rule
  description: Recorded Future risk rule name
  type: string
- contextPath: RecordedFuture.CVE.Evidence.mitigation
  description: Recorded Future risk rule mitigation
  type: string
- contextPath: RecordedFuture.CVE.Evidence.description
  description: Recorded Future risk rule description
  type: string
- contextPath: RecordedFuture.CVE.Evidence.timestamp
  description: Recorded Future risk rule timestamp
  type: date
- contextPath: RecordedFuture.CVE.Evidence.level
  description: Recorded Future risk rule level
  type: number
- contextPath: RecordedFuture.CVE.Evidence.ruleid
  description: Recorded Future risk rule ID
  type: string
- contextPath: RecordedFuture.CVE.name
  description: Vulnerability name
  type: string
- contextPath: RecordedFuture.CVE.maxRules
  description: Maximum count of Recorded Future vulnerability risk rules
  type: number
- contextPath: RecordedFuture.CVE.ruleCount
  description: Number of triggered Recorded Future vulnerability risk rules
  type: number
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 89ea0694-d9c9-4ddf-8fd0-135f159afb57
      iscommand: false
      name: ""
      version: -1
    taskid: 89ea0694-d9c9-4ddf-8fd0-135f159afb57
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.CVE
          operator: isExists
      label: "yes"
    id: "16"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "29"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether the playbook's input contains at least one domain
        name for which to retrieve the reputation.
      id: 2b22eb54-802e-4d08-88da-3435a0e282da
      iscommand: false
      name: Is there a CVE ID to get reputation of?
      type: condition
      version: -1
    taskid: 2b22eb54-802e-4d08-88da-3435a0e282da
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "24":
    id: "24"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9b1db93f-3933-43ee-89cd-df000c5047a2
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 9b1db93f-3933-43ee-89cd-df000c5047a2
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
  "26":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: containsString
                    right:
                      value:
                        simple: Recorded Future
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "26"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Recorded Future API
        integration enabled.
      id: 4729ec6c-7996-4e59-88c7-f9621b41d451
      iscommand: false
      name: Is Recorded Future API enabled?
      type: condition
      version: -1
    taskid: 4729ec6c-7996-4e59-88c7-f9621b41d451
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 410,
          "y": 505
        }
      }
  "28":
    id: "28"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      cve:
        simple: ${inputs.CVE}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Get a quick indicator of the risk associated with a specific CVE.
      id: a2869b99-0dfa-4009-8feb-b03dd23bf17d
      iscommand: true
      name: Get CVE reputation from Recorded Future
      script: Recorded Future v2|||cve
      type: regular
      version: -1
    taskid: a2869b99-0dfa-4009-8feb-b03dd23bf17d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 410,
          "y": 730
        }
      }
  "29":
    id: "29"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8075d9ed-0723-4435-8018-09dc88e18081
      iscommand: false
      name: Get reputation using Recorded Future API
      type: title
      version: -1
    taskid: 8075d9ed-0723-4435-8018-09dc88e18081
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 410,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "16_24_#default#": 0.57,
      "26_24_#default#": 0.55,
      "26_28_yes": 0.61
    },
    "paper": {
      "dimensions": {
        "height": 880,
        "width": 740,
        "x": 50,
        "y": 50
      }
    }
  }
