contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: 1.1.6
    packID: TIM_Processing
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: This playbook processes indicators to check if they exist in a Cortex
  XSOAR list containing the organizational External IP addresses, and tags the indicators
  accordingly.
id: TIM - Process Indicators Against Organizations External IP List
inputs:
- description: ""
  key: ""
  playbookInputQuery:
    daterange:
      fromdate: "0001-01-01T00:00:00Z"
      fromdatelicenseval: "0001-01-01T00:00:00Z"
      period:
        by: ""
        byfrom: ""
        byto: ""
        field: ""
        fromvalue: null
        tovalue: null
      todate: "0001-01-01T00:00:00Z"
    query: ""
    queryEntity: indicators
    results: null
    runFromLastJobTime: false
  required: false
  value: {}
- description: A Cortex XSOAR list containing the organization's External IP address
    values. IP Indicators that appear in the list are tagged as organizations external
    ip.
  key: OrganizationsExternalIPListName
  playbookInputQuery: null
  required: false
  value: {}
name: TIM - Process Indicators Against Organizations External IP List
outputs:
- contextPath: OrganizationExternalIP
  description: IP addresses that are found in the  organization's external IP list.
  type: string
- contextPath: NotOrganizationExternalIP
  description: IP addresses that are not found in the organization's external IP list.
  type: string
quiet: true
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "19"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 78e61b73-8045-41d4-8937-e6a0fde8c8f7
      iscommand: false
      name: ""
      version: -1
    taskid: 78e61b73-8045-41d4-8937-e6a0fde8c8f7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 510,
          "y": -1390
        }
      }
  "19":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: playbookQuery.indicator_type
          operator: isEqualString
          right:
            value:
              simple: IP
      label: "yes"
    id: "19"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "105"
      "yes":
      - "101"
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 04dc01d7-614f-4d7a-8353-293b6599232a
      iscommand: false
      name: Are there IP results?
      type: condition
      version: -1
    taskid: 04dc01d7-614f-4d7a-8353-293b6599232a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 510,
          "y": -1260
        }
      }
  "101":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.OrganizationsExternalIPListName
          operator: isNotEmpty
      label: "yes"
    id: "101"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "108"
      "yes":
      - "102"
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8ebd9515-964d-4567-8d9c-26fe031145ca
      iscommand: false
      name: Is there an organizations external IP list
      type: condition
      version: -1
    taskid: 8ebd9515-964d-4567-8d9c-26fe031145ca
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 270,
          "y": -1090
        }
      }
  "102":
    id: "102"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "106"
      - "107"
    note: false
    quietmode: 2
    scriptarguments:
      ignorecase:
        simple: "yes"
      listname:
        simple: ${inputs.OrganizationsExternalIPListName}
      matchexact:
        simple: "yes"
      values:
        simple: ${playbookQuery.value}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether the specified item is in a Cortex XSOAR list.
      id: bc844da7-9456-4252-8f8a-72da44e1b5be
      iscommand: false
      name: Run filter by list check on indicators
      script: FilterByList
      type: regular
      version: -1
    taskid: bc844da7-9456-4252-8f8a-72da44e1b5be
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 30,
          "y": -920
        }
      }
  "103":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: List.In
          operator: isNotEmpty
      label: "yes"
    id: "103"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "105"
      "yes":
      - "104"
    note: false
    quietmode: 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c36084d8-2779-4728-8e5d-6b002b13c977
      iscommand: false
      name: Do values appear in organizations external IP list?
      type: condition
      version: -1
    taskid: c36084d8-2779-4728-8e5d-6b002b13c977
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 280,
          "y": -580
        }
      }
  "104":
    id: "104"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "105"
    note: false
    quietmode: 2
    scriptarguments:
      field:
        simple: tags
      fieldValue:
        simple: organizational_external_ip
      indicatorsValues:
        complex:
          accessor: In
          root: List
          transformers:
          - operator: uniq
      value:
        simple: ${List.In}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: Add organizations external IP tag to indicators
      id: 7781ca91-08b9-4831-823a-95bf09b5eeb6
      iscommand: true
      name: Add organizations external IP tag to indicators
      script: Builtin|||appendIndicatorField
      type: regular
      version: -1
    taskid: 7781ca91-08b9-4831-823a-95bf09b5eeb6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 100,
          "y": -410
        }
      }
  "105":
    id: "105"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 33154239-54b9-4257-8b01-e5c4466197c9
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 33154239-54b9-4257-8b01-e5c4466197c9
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 510,
          "y": -240
        }
      }
  "106":
    id: "106"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "103"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: OrganizationExternalIP
      stringify: {}
      value:
        simple: ${List.In}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the specified value exists in context. If the value exists,
        it is set in context, otherwise no value is set in context.
      id: 4ca341a5-9bb4-4975-8861-4c1833cffe75
      iscommand: false
      name: Set values in list
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: 4ca341a5-9bb4-4975-8861-4c1833cffe75
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -370,
          "y": -750
        }
      }
  "107":
    id: "107"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "103"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: NotOrganizationExternalIP
      stringify: {}
      value:
        simple: ${List.NotIn}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the specified value exists in context. If the value exists,
        it is set in context, otherwise no value is set in context.
      id: 68230d8c-8cc7-4bc1-85be-589921c4eca6
      iscommand: false
      name: Set values not in list
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: 68230d8c-8cc7-4bc1-85be-589921c4eca6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 30,
          "y": -750
        }
      }
  "108":
    id: "108"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "105"
    note: false
    quietmode: 0
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: NotOrganizationExternalIP
      stringify: {}
      value:
        complex:
          accessor: value
          filters:
          - - left:
                iscontext: true
                value:
                  simple: playbookQuery.indicator_type
              operator: isEqualString
              right:
                value:
                  simple: IP
          root: playbookQuery
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if the specified value exists in context. If the value exists,
        it is set in context, otherwise no value is set in context.
      id: d7935011-426d-4ff2-8c8e-6eb41895895d
      iscommand: false
      name: Set values
      script: SetAndHandleEmpty
      type: regular
      version: -1
    taskid: d7935011-426d-4ff2-8c8e-6eb41895895d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 740,
          "y": -920
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1215,
        "width": 1490,
        "x": -370,
        "y": -1390
      }
    }
  }
