contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: 1.0.3
    packID: Silverfort
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: This playbook gets the user risk from Silverfort DB. If the risk is medium
  or higher, the user will be blocked & alert will be sent.
id: Silverfort Disable High Risk Account
inputs:
- description: Account Username
  key: Username
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Username
      root: Account
      transformers:
      - operator: uniq
- description: Set to true if you want the playbook to automatically disable the account
  key: AutomaticDisable
  playbookInputQuery: null
  required: false
  value:
    simple: "False"
name: Silverfort Disable High Risk Account
outputs:
- contextPath: Silverfort.UserRisk.Risk
  description: Risk level
- contextPath: Silverfort.UserRisk.Reasons
  description: Risk reasons
- contextPath: Silverfort.UserRisk.UPN
  description: User principal name
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "11"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 91ebdb53-730d-45a6-827a-e5f42c428da4
      iscommand: false
      name: ""
      version: -1
    taskid: 91ebdb53-730d-45a6-827a-e5f42c428da4
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      domain:
        complex:
          accessor: Users.dn}
          root: ${ActiveDirectory
          transformers:
          - args:
              error_if_no_match: {}
              ignore_case: {}
              multi_line: {}
              period_matches_newline: {}
              regex:
                value:
                  simple: DC=([^,]*)
            operator: RegexExtractAll
          - args:
              separator:
                value:
                  simple: .
            operator: join
      email: {}
      sam_account:
        simple: ${ActiveDirectory.Users.sAMAccountName}
      upn: {}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: User risk commands - get the user entity risk
      id: 7a55238d-b08c-49ad-8dbc-3848992ddd9e
      iscommand: true
      name: Get User Risk from Silverfort
      script: '|||silverfort-get-user-risk'
      type: regular
      version: -1
    taskid: 7a55238d-b08c-49ad-8dbc-3848992ddd9e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
  "5":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Silverfort.UserRisk.Risk
          operator: isEqualString
          right:
            value:
              simple: High
        - left:
            iscontext: true
            value:
              simple: Silverfort.UserRisk.Risk
          operator: isEqualString
          right:
            value:
              simple: Critical
      label: High Or Critical
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Silverfort.UserRisk.Risk
          operator: isEqualString
          right:
            value:
              simple: Low
        - left:
            iscontext: true
            value:
              simple: Silverfort.UserRisk.Risk
          operator: isEqualString
          right:
            value:
              simple: Medium
      label: Low Or Medium
    id: "5"
    ignoreworker: false
    nexttasks:
      High Or Critical:
      - "7"
      Low Or Medium:
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check the user risk
      id: 0147e2f8-cf60-4d5f-8577-ba1c9c293e9e
      iscommand: false
      name: Check Silverfort User Risk
      type: condition
      version: -1
    taskid: 0147e2f8-cf60-4d5f-8577-ba1c9c293e9e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
  "7":
    id: "7"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "12"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 44425412-ffb6-448b-8856-70bb40bed260
      iscommand: false
      name: Block the user in AD
      type: title
      version: -1
    taskid: 44425412-ffb6-448b-8856-70bb40bed260
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
  "8":
    id: "8"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 188a26df-64a3-45a0-812e-da38fe611048
      iscommand: false
      name: Do Nothing
      type: title
      version: -1
    taskid: 188a26df-64a3-45a0-812e-da38fe611048
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 807.5,
          "y": 895
        }
      }
  "10":
    id: "10"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      Username:
        complex:
          root: inputs.Username
          transformers:
          - operator: uniq
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Enrich accounts using one or more integrations.
        Supported integrations:
        - Active Directory
      id: 65a1185c-1e4d-4699-8c0e-366ad708e6f8
      iscommand: false
      name: Account Enrichment - Generic v2.1
      playbookId: Account Enrichment - Generic v2.1
      type: playbook
      version: -1
    taskid: 65a1185c-1e4d-4699-8c0e-366ad708e6f8
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: isEqualString
                    right:
                      value:
                        simple: Silverfort
                - - left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "11"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Check if Silverfort is enabled
      id: 1605e45b-778c-4819-8931-12e277208240
      iscommand: false
      name: Is Silverfort enabled ?
      type: condition
      version: -1
    taskid: 1605e45b-778c-4819-8931-12e277208240
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
  "12":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: inputs.AutomaticDisable
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    id: "12"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "14"
      "yes":
      - "13"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: 'Is Automatic Disable True '
      id: 885afe30-ac8a-4ff7-844e-dd2d0e78f453
      iscommand: false
      name: Is Automatic Disable True ?
      type: condition
      version: -1
    taskid: 885afe30-ac8a-4ff7-844e-dd2d0e78f453
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1040
        }
      }
  "13":
    id: "13"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    scriptarguments:
      base-dn: {}
      username:
        simple: ${ActiveDirectory.Users.sAMAccountName}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Disables an Active Directory user account.
      id: 177e597e-e14a-45e5-8f0e-8ed10d7639a6
      iscommand: true
      name: AD Disable Account
      script: '|||ad-disable-account'
      type: regular
      version: -1
    taskid: 177e597e-e14a-45e5-8f0e-8ed10d7639a6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1215
        }
      }
  "14":
    id: "14"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "15"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Manually Disable Account
      id: 38fbac3e-c93b-410a-8b43-c9a768409804
      iscommand: false
      name: Manually Disable Account
      type: regular
      version: -1
    taskid: 38fbac3e-c93b-410a-8b43-c9a768409804
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1215
        }
      }
  "15":
    id: "15"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 59f83391-144d-462e-84cf-525dd77b3b8e
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 59f83391-144d-462e-84cf-525dd77b3b8e
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1390
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1405,
        "width": 1137.5,
        "x": 50,
        "y": 50
      }
    }
  }
