contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: 1.0.2
    packID: RecordedFuture
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: Domain enrichment using Recorded Future intelligence
id: Recorded Future Domain Intelligence
inputs:
- description: The domain name to enrich.
  key: Domain
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Name
      root: Domain
name: Recorded Future Domain Intelligence
outputs:
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
  type: string
- contextPath: DBotScore.Type
  description: Indicator type
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: Domain.Name
  description: Domain name
  type: string
- contextPath: RecordedFuture.Domain.criticality
  description: Risk Criticality
  type: number
- contextPath: RecordedFuture.Domain.criticalityLabel
  description: Risk Criticality Label
  type: string
- contextPath: RecordedFuture.Domain.riskString
  description: Risk String
  type: string
- contextPath: RecordedFuture.Domain.riskSummary
  description: Risk Summary
  type: string
- contextPath: RecordedFuture.Domain.rules
  description: Risk Rules
  type: string
- contextPath: RecordedFuture.Domain.score
  description: Risk Score
  type: number
- contextPath: RecordedFuture.Domain.firstSeen
  description: Evidence First Seen
  type: date
- contextPath: RecordedFuture.Domain.lastSeen
  description: Evidence Last Seen
  type: date
- contextPath: RecordedFuture.Domain.intelCard
  description: Recorded Future Intelligence Card URL
  type: string
- contextPath: RecordedFuture.Domain.type
  description: Entity Type
  type: string
- contextPath: RecordedFuture.Domain.name
  description: Entity
  type: string
- contextPath: RecordedFuture.Domain.id
  description: Recorded Future Entity ID
  type: string
- contextPath: RecordedFuture.Domain.metrics.type
  description: Recorded Future Metrics Type
  type: string
- contextPath: RecordedFuture.Domain.metrics.value
  description: Recorded Future Metrics Value
  type: number
- contextPath: RecordedFuture.Domain.threatLists.description
  description: Recorded Future Threat List Description
  type: string
- contextPath: RecordedFuture.Domain.threatLists.id
  description: Recorded Future Threat List ID
  type: string
- contextPath: RecordedFuture.Domain.threatLists.name
  description: Recorded Future Threat List Name
  type: string
- contextPath: RecordedFuture.Domain.threatLists.type
  description: Recorded Future Threat List Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedAttacker.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedAttacker.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedAttacker.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedAttacker.type
  description: Recorded Future Related Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedTarget.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedTarget.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedTarget.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedTarget.type
  description: Recorded Future Related Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedThreatActor.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedThreatActor.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedThreatActor.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedThreatActor.type
  description: Recorded Future Related Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedMalware.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedMalware.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedMalware.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedMalware.type
  description: Recorded Future Related Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedCyberVulnerability.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedCyberVulnerability.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedCyberVulnerability.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedCyberVulnerability.type
  description: Recorded Future Related Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedIpAddress.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedIpAddress.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedIpAddress.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedIpAddress.type
  description: Recorded Future Related Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedInternetDomainName.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedInternetDomainName.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedInternetDomainName.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedInternetDomainName.type
  description: Recorded Future Related Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedProduct.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedProduct.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedProduct.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedProduct.type
  description: Recorded Future Related Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedCountries.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedCountries.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedCountries.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedCountries.type
  description: Recorded Future Related Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedHash.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedHash.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedHash.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedHash.type
  description: Recorded Future Related Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedTechnology.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedTechnology.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedTechnology.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedTechnology.type
  description: Recorded Future Related Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedEmailAddress.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedEmailAddress.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedEmailAddress.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedEmailAddress.type
  description: Recorded Future Related Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedAttackVector.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedAttackVector.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedAttackVector.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedAttackVector.type
  description: Recorded Future Related Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedMalwareCategory.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedMalwareCategory.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedMalwareCategory.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedMalwareCategory.type
  description: Recorded Future Related Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedOperations.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedOperations.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedOperations.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedOperations.type
  description: Recorded Future Related Type
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedCompany.count
  description: Recorded Future Related Count
  type: number
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedCompany.id
  description: Recorded Future Related ID
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedCompany.name
  description: Recorded Future Related Name
  type: string
- contextPath: RecordedFuture.Domain.relatedEntities.RelatedCompany.type
  description: Recorded Future Related Type
  type: string
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 89ea0694-d9c9-4ddf-8fd0-135f159afb57
      iscommand: false
      name: ""
      version: -1
    taskid: 89ea0694-d9c9-4ddf-8fd0-135f159afb57
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.Domain
          operator: isExists
      label: "yes"
    id: "16"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "29"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether the playbook's input contains at least one domain
        name to enrich.
      id: 3c6fe423-8215-4bd0-8bf5-c57c35889637
      iscommand: false
      name: Is there a domain to enrich?
      type: condition
      version: -1
    taskid: 3c6fe423-8215-4bd0-8bf5-c57c35889637
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "24":
    id: "24"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9b1db93f-3933-43ee-89cd-df000c5047a2
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 9b1db93f-3933-43ee-89cd-df000c5047a2
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
  "26":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: containsString
                    right:
                      value:
                        simple: Recorded Future
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "26"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Recorded Future API
        integration enabled.
      id: 3b354965-eea8-4788-8823-1fba55a9f03a
      iscommand: false
      name: Is Recorded Future API enabled?
      type: condition
      version: -1
    taskid: 3b354965-eea8-4788-8823-1fba55a9f03a
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 410,
          "y": 505
        }
      }
  "28":
    id: "28"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      entity:
        simple: ${inputs.Domain}
      entity_type:
        simple: domain
      fetch_related_entities:
        simple: "yes"
      fetch_riskyCIDRips:
        simple: "no"
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Get threat intelligence for an IP, domain, CVE, URL, or file.
      id: f4ac0b12-f3ed-4d27-8ba6-c9b8c70202b6
      iscommand: true
      name: Get domain intelligence from Recorded Future
      script: Recorded Future v2|||recordedfuture-intelligence
      type: regular
      version: -1
    taskid: f4ac0b12-f3ed-4d27-8ba6-c9b8c70202b6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 410,
          "y": 730
        }
      }
  "29":
    id: "29"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8075d9ed-0723-4435-8018-09dc88e18081
      iscommand: false
      name: Enrich Using Recorded Future API
      type: title
      version: -1
    taskid: 8075d9ed-0723-4435-8018-09dc88e18081
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 410,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "16_24_#default#": 0.57,
      "26_24_#default#": 0.55,
      "26_28_yes": 0.61
    },
    "paper": {
      "dimensions": {
        "height": 880,
        "width": 740,
        "x": 50,
        "y": 50
      }
    }
  }
