contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: 1.0.2
    packID: RecordedFuture
    packPropagationLabels:
    - all
    propagationLabels: []
    toServerVersion: ""
description: Threat Assessment using the Recorded Future SOAR Triage API and the context
  Phishing.
id: Recorded Future Threat Assessment
inputs:
- description: CVE ID to check if it is related to the C2 context.
  key: CVE
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: ID
      root: CVE
      transformers:
      - operator: uniq
- description: IP Address to check if it is related to the C2 context.
  key: IP
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Address
      root: IP
      transformers:
      - operator: uniq
- description: URL to check if it is related to the C2 context.
  key: URL
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Data
      root: URL
      transformers:
      - operator: uniq
- description: MD5 to check if it is related to the C2 context.
  key: MD5
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: MD5
      root: File
      transformers:
      - operator: uniq
- description: SHA-1 to check if it is related to the C2 context.
  key: SHA1
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA1
      root: File
      transformers:
      - operator: uniq
- description: SHA-256 to check if it is related to the C2 context.
  key: SHA256
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: SHA256
      root: File
      transformers:
      - operator: uniq
- description: Domain to check if it is related to the C2 context.
  key: Domain
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: Name
      root: Domain
      transformers:
      - operator: uniq
- description: Context to use for assessment. This is used by Recorded Future to calculate
    the relevant score and verdict. Valid values are "c2", "malware" and "phishing".
  key: threat-assessment-context
  playbookInputQuery: null
  required: true
  value:
    simple: phishing
name: Recorded Future Threat Assessment
outputs:
- contextPath: DBotScore.Indicator
  description: The indicator that was tested
  type: string
- contextPath: DBotScore.Type
  description: Indicator type
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
- contextPath: File.SHA256
  description: SHA-256
  type: string
- contextPath: File.SHA512
  description: SHA-512
  type: string
- contextPath: File.SHA1
  description: SHA-1
  type: string
- contextPath: File.MD5
  description: MD5
  type: string
- contextPath: File.CRC32
  description: CRC32
  type: string
- contextPath: File.CTPH
  description: CTPH
  type: string
- contextPath: IP.Address
  description: IP address
  type: string
- contextPath: IP.ASN
  description: ASN
  type: string
- contextPath: IP.Geo.Country
  description: IP Geolocation Country
  type: string
- contextPath: Domain.Name
  description: Domain name
  type: string
- contextPath: URL.Data
  description: URL name
  type: string
- contextPath: CVE.ID
  description: Vulnerability name
  type: string
- contextPath: RecordedFuture.verdict
  description: Recorded Future verdict
  type: boolean
- contextPath: RecordedFuture.context
  description: Threat Assessment Context
  type: string
- contextPath: RecordedFuture.riskScore
  description: Recorded Future Max Score
  type: number
- contextPath: RecordedFuture.Entities.id
  description: Entity ID
  type: string
- contextPath: RecordedFuture.Entities.name
  description: Entity Name
  type: string
- contextPath: RecordedFuture.Entities.type
  description: Entity Type
  type: string
- contextPath: RecordedFuture.Entities.score
  description: Entity Score
  type: string
- contextPath: RecordedFuture.Entities.Evidence.ruleid
  description: Recorded Future Risk Rule ID
  type: string
- contextPath: RecordedFuture.Entities.Evidence.timestamp
  description: Recorded Future Evidence Timestamp
  type: date
- contextPath: RecordedFuture.Entities.Evidence.mitigation
  description: Recorded Future Evidence Mitigation
  type: string
- contextPath: RecordedFuture.Entities.Evidence.description
  description: Recorded Future Evidence Description
  type: string
- contextPath: RecordedFuture.Entities.Evidence.rule
  description: Recorded Future Risk Rule
  type: string
- contextPath: RecordedFuture.Entities.Evidence.level
  description: Recorded Future Risk Rule Level
  type: number
starttaskid: "0"
system: true
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "16"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 70db8e96-a768-4f64-89de-4f822c87d694
      iscommand: false
      name: ""
      version: -1
    taskid: 70db8e96-a768-4f64-89de-4f822c87d694
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "16":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: inputs.CVE
          operator: isExists
        - left:
            iscontext: true
            value:
              simple: inputs.IP
          operator: isExists
        - left:
            iscontext: true
            value:
              simple: inputs.URL
          operator: isExists
        - left:
            iscontext: true
            value:
              simple: inputs.MD5
          operator: isExists
        - left:
            iscontext: true
            value:
              simple: inputs.SHA1
          operator: isExists
        - left:
            iscontext: true
            value:
              simple: inputs.SHA256
          operator: isExists
        - left:
            iscontext: true
            value:
              simple: inputs.Domain
          operator: isExists
      label: "yes"
    id: "16"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "29"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks whether the playbook's input contains at least one domain
        name to enrich.
      id: 6c3bda0e-4e5a-414e-89ae-09ff9087f150
      iscommand: false
      name: Is there anything to assess?
      type: condition
      version: -1
    taskid: 6c3bda0e-4e5a-414e-89ae-09ff9087f150
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "24":
    id: "24"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7f5f8c9f-b25b-4a7a-854b-553dc88f1c54
      iscommand: false
      name: Done
      type: title
      version: -1
    taskid: 7f5f8c9f-b25b-4a7a-854b-553dc88f1c54
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1005
        }
      }
  "26":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: brand
                filters:
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.brand
                    operator: containsString
                    right:
                      value:
                        simple: Recorded Future
                - - ignorecase: true
                    left:
                      iscontext: true
                      value:
                        simple: modules.state
                    operator: isEqualString
                    right:
                      value:
                        simple: active
                root: modules
          operator: isExists
      label: "yes"
    id: "26"
    ignoreworker: false
    nexttasks:
      '#default#':
      - "24"
      "yes":
      - "28"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Checks if there is an active instance of the Recorded Future API
        integration enabled.
      id: 2bb4b3b1-3c77-447b-8cce-2d600641142e
      iscommand: false
      name: Is Recorded Future API enabled?
      type: condition
      version: -1
    taskid: 2bb4b3b1-3c77-447b-8cce-2d600641142e
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 410,
          "y": 505
        }
      }
  "28":
    id: "28"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "24"
    note: false
    quietmode: 0
    reputationcalc: 1
    scriptarguments:
      context:
        simple: ${inputs.threat-assessment-context}
      cve:
        simple: ${inputs.CVE}
      domain:
        simple: ${inputs.Domain}
      file:
        simple: ${inputs.MD5},${inputs.SHA1},${inputs.SHA256}
      ip:
        simple: ${inputs.IP}
      url:
        simple: ${inputs.URL}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Recorded Future v2
      description: Get an indication of the risk based on context.
      id: e9f5bca8-94bd-4b41-83b4-b97b9f47599b
      iscommand: true
      name: Get Threat Assessment from Recorded Future
      script: Recorded Future v2|||recordedfuture-threat-assessment
      type: regular
      version: -1
    taskid: e9f5bca8-94bd-4b41-83b4-b97b9f47599b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 410,
          "y": 820
        }
      }
  "29":
    id: "29"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "26"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 6f7224be-bf6f-4080-842d-c3196a87c951
      iscommand: false
      name: Threat Assessment Using Recorded Future API
      type: title
      version: -1
    taskid: 6f7224be-bf6f-4080-842d-c3196a87c951
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 410,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "16_24_#default#": 0.57
    },
    "paper": {
      "dimensions": {
        "height": 1020,
        "width": 740,
        "x": 50,
        "y": 50
      }
    }
  }
